name: Build and Release

on:
  push:
    tags:
      - 'v*' # v1.1.1 gibi bir etiket (tag) gönderildiğinde çalışır
  workflow_dispatch: # Manuel olarak da başlatabilmeniz için

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build and Publish
        run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
